type = "directrequest"
schemaVersion = 1
externalJobID = "235bbeca-65f3-44b7-ba8b-3af501e43622"
requesters = [
    "0x7e70aBA8171e0bCf02AA40b5DAB64FF24b622C2a"
] # Replace with DRCoordinator.sol address (1 of 3)
minContractPaymentLinkJuels = "5000000000000000" # 0.005 LINK
name = "Sportsdataio LinkPool Get Schedule v1.0.0 DRCoordinator"
contractAddress = "0x878541888a928a31F9EAb4cB61DfD4e381EC2f00" # Replace with Operator.sol address (2 of 3)
maxTaskDuration = "0s"
observationSource = """
    decode_log          [type="ethabidecodelog"
                         abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                         data="$(jobRun.logData)"
                         topics="$(jobRun.logTopics)"]

    decode_cbor         [type="cborparse" data="$(decode_log.data)"]

    merge_req_params    [type="merge" left="{\\"gameIds\\": null}" right="$(decode_cbor)"]

    sportsdataio_lp     [type="bridge"
                         name="sportsdataio_lp"
                         requestData="{\\"data\\": {\\"endpoint\\": \\"schedule\\",\\"market\\": $(merge_req_params.market), \\"leagueId\\": $(merge_req_params.leagueId), \\"date\\": $(merge_req_params.date), \\"gameIds\\": $(merge_req_params.gameIds)}}"]

    parse_result        [type="jsonparse" data="$(sportsdataio_lp)" path="result"]

    encode_data         [type="ethabiencode"
                         abi="(bytes32 _requestId, bytes32[] _result)"
                         data="{\\"_requestId\\": $(decode_log.requestId),\\"_result\\": $(parse_result)}"]

    encode_tx           [type="ethabiencode"
                         abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                         data="{\\"requestId\\": $(decode_log.requestId),\\"payment\\": $(decode_log.payment),\\"callbackAddress\\": $(decode_log.callbackAddr),\\"callbackFunctionId\\": $(decode_log.callbackFunctionId),\\"expiration\\": $(decode_log.cancelExpiration),\\"data\\": $(encode_data)}"]

    submit_tx           [type="ethtx" to="0x878541888a928a31F9EAb4cB61DfD4e381EC2f00" data="$(encode_tx)" minConfirmations="$(decode_cbor.minConfirmations)" gasLimit="$(decode_cbor.gasLimit)"] // Replace with Operator.sol address (3 of 3)

    decode_log -> decode_cbor -> merge_req_params -> sportsdataio_lp -> parse_result -> encode_data -> encode_tx -> submit_tx
"""
